name: Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
    push:
        branches:
          - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
    
        steps:
            - name: Install Vercel CLI
              run: npm install --global vercel
            
            - name: Pull Vercel Envirement Information
              run: vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}}

            - name: Build Vercel Project
              run: vercel build --prod --token=${{secrets.VERCEL_TOKEN}}
            
            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}
        
            
       
